//! HMI project skeleton generation.
//!
//! Creates the initial `hmi/` directory structure with default
//! configuration files and page templates.

use std::path::Path;

use crate::project::ProjectLoader;

/// Generate an HMI project skeleton at `out_dir`.
///
/// # Errors
///
/// Returns an error if the directory cannot be created or files cannot
/// be written.
pub fn generate_skeleton(
    _loader: &ProjectLoader,
    out_dir: &Path,
    style: &str,
) -> anyhow::Result<()> {
    std::fs::create_dir_all(out_dir)?;

    let style = style.trim().to_ascii_lowercase();
    let palette = theme_palette(&style)
        .unwrap_or_else(|| theme_palette("industrial").expect("industrial theme always exists"));

    // _config.toml — global HMI configuration
    let config_toml = format!(
        r#"# HMI Configuration — generated by trust-hmi-gen
version = 1

[theme]
style = "{style}"
accent = "{accent}"

[layout]
navigation = "sidebar"
header = true
header_title = "ST Project HMI"

[write]
enabled = false
allow = []
"#,
        style = style,
        accent = palette.accent,
    );

    // overview.toml — main dashboard page
    let overview_toml = r#"# Overview page — auto-generated
id = "overview"
title = "Overview"
order = 0
kind = "dashboard"

[[section]]
title = "General"
span = 12

# Widgets will be inserted here by the bindings command
# [[section.widget]]
# type = "value"
# bind = "Program.MyVariable"
# label = "My Variable"
"#;

    // trends.toml — trend/historian page
    let trends_toml = r#"# Trends page
id = "trends"
title = "Trends"
order = 50
kind = "trend"
duration_ms = 600000

signals = []
"#;

    // alarms.toml — alarm summary page
    let alarms_toml = r#"# Alarms page
id = "alarms"
title = "Alarms"
order = 60
kind = "alarm"
"#;

    // control.toml — setpoints and commands
    let control_toml = r#"# Control page
id = "control"
title = "Control"
order = 30
kind = "dashboard"

[[section]]
title = "Setpoints"
span = 6

[[section]]
title = "Commands"
span = 6
"#;

    std::fs::write(out_dir.join("_config.toml"), config_toml)?;
    std::fs::write(out_dir.join("overview.toml"), overview_toml)?;
    std::fs::write(out_dir.join("trends.toml"), trends_toml)?;
    std::fs::write(out_dir.join("alarms.toml"), alarms_toml)?;
    std::fs::write(out_dir.join("control.toml"), control_toml)?;

    Ok(())
}

/// Theme color palette for scaffold generation.
struct ThemePalette {
    #[allow(dead_code)]
    style: &'static str,
    accent: &'static str,
    #[allow(dead_code)]
    background: &'static str,
    #[allow(dead_code)]
    surface: &'static str,
    #[allow(dead_code)]
    text: &'static str,
}

fn theme_palette(style: &str) -> Option<ThemePalette> {
    match style {
        "classic" => Some(ThemePalette {
            style: "classic",
            accent: "#0f766e",
            background: "#f3f5f8",
            surface: "#ffffff",
            text: "#142133",
        }),
        "industrial" => Some(ThemePalette {
            style: "industrial",
            accent: "#c2410c",
            background: "#f5f3ef",
            surface: "#ffffff",
            text: "#221a14",
        }),
        "mint" => Some(ThemePalette {
            style: "mint",
            accent: "#0d9488",
            background: "#ecfdf5",
            surface: "#f8fffc",
            text: "#0b3b35",
        }),
        "control-room" => Some(ThemePalette {
            style: "control-room",
            accent: "#14b8a6",
            background: "#0f1115",
            surface: "#171a21",
            text: "#f2f2f2",
        }),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_themes_exist() {
        assert!(theme_palette("classic").is_some());
        assert!(theme_palette("industrial").is_some());
        assert!(theme_palette("mint").is_some());
        assert!(theme_palette("control-room").is_some());
    }

    #[test]
    fn unknown_theme_returns_none() {
        assert!(theme_palette("unknown").is_none());
    }
}
